version: "3"
services:
  gk-server:
    restart: 'unless-stopped'
    image: golang:1.18-alpine
    volumes:
      - './bin/:/root/gk-server/'
    working_dir: /root/gk-server/
    entrypoint: /root/gk-server/gk-server
    environment:
      DATABASE_URI: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
    links:
      - postgres
  postgres:
    restart: 'unless-stopped'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata:
